vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        aliment_image:
            uri_prefix: /images/aliments
            upload_destination: '%kernel.project_dir%/public/images/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer